SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `host`
ADD COLUMN `is_debug` TINYINT(1) NULL DEFAULT NULL AFTER `public_key`;

CREATE TABLE IF NOT EXISTS `db` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `host_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_db_host1_idx` (`host_id` ASC),
  CONSTRAINT `fk_db_host1`
    FOREIGN KEY (`host_id`)
    REFERENCES `host` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `db_link` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `db_id` INT(11) NOT NULL,
  `app_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_db_link_db1_idx` (`db_id` ASC),
  INDEX `fk_db_link_app1_idx` (`app_id` ASC),
  CONSTRAINT `fk_db_link_db1`
    FOREIGN KEY (`db_id`)
    REFERENCES `db` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_db_link_app1`
    FOREIGN KEY (`app_id`)
    REFERENCES `app` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `config` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `value` TEXT NULL DEFAULT NULL,
  `app_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_config_app1_idx` (`app_id` ASC),
  CONSTRAINT `fk_config_app1`
    FOREIGN KEY (`app_id`)
    REFERENCES `app` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `domain` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `app_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_domain_app1_idx` (`app_id` ASC),
  CONSTRAINT `fk_domain_app1`
    FOREIGN KEY (`app_id`)
    REFERENCES `app` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `host_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `host_id` INT(11) NOT NULL,
  `line` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_host_log_host1_idx` (`host_id` ASC),
  CONSTRAINT `fk_host_log_host1`
    FOREIGN KEY (`host_id`)
    REFERENCES `host` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

ALTER TABLE `host_log`
ADD COLUMN `ts` datetime NULL DEFAULT NULL AFTER `host_id`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
